sudo: required

language: generic

addons:
  apt:
    packages:
    - snapd

before_install:
  - export PATH=$PATH:/snap/bin

install:
  - sudo snap install --channel=extended hugo
  - ./bin/build

script:
  - ./bin/test
